-- =============================================================================
-- Migration: Create block_forecasts table in Supabase PostgreSQL
-- Timestamp: 2026-09-06
-- Description: Stores raw regional numerical rainfall forecasts from IMD
-- =============================================================================

CREATE TABLE IF NOT EXISTS block_forecasts (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    district_name TEXT NOT NULL,
    block_name TEXT NOT NULL,
    forecast_issue_date DATE NOT NULL,
    forecast_date DATE NOT NULL,
    rainfall_mm NUMERIC NOT NULL,
    source TEXT,
    source_model TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    
    -- Uniqueness constraint across district, block, issue date, target date, and source model
    CONSTRAINT uq_block_forecasts UNIQUE (
        district_name,
        block_name,
        forecast_issue_date,
        forecast_date,
        source_model
    )
);

-- =============================================================================
-- INDEXES FOR FAST QUERYING & TEMPORAL LOOKUPS
-- =============================================================================

-- 1. Composite index on district_name and block_name for fast spatial queries
CREATE INDEX IF NOT EXISTS idx_block_forecasts_district_block 
ON block_forecasts (district_name, block_name);

-- 2. Index on forecast_date for daily horizon queries
CREATE INDEX IF NOT EXISTS idx_block_forecasts_forecast_date 
ON block_forecasts (forecast_date);

-- 3. Index on forecast_issue_date for tracking forecast runs and issue latency
CREATE INDEX IF NOT EXISTS idx_block_forecasts_forecast_issue_date 
ON block_forecasts (forecast_issue_date);

-- =============================================================================
-- TABLE & COLUMN DOCUMENTATION COMMENTS
-- =============================================================================

COMMENT ON TABLE block_forecasts IS 'Raw numerical weather prediction (NWP) rainfall forecasts at Block level issued by IMD/NCMRWF.';
COMMENT ON COLUMN block_forecasts.id IS 'Unique identifier auto-generated as identity.';
COMMENT ON COLUMN block_forecasts.district_name IS 'Administrative district name (e.g., Nashik).';
COMMENT ON COLUMN block_forecasts.block_name IS 'Administrative block/taluka name (e.g., Dindori, Surgana).';
COMMENT ON COLUMN block_forecasts.forecast_issue_date IS 'Date on which the numerical weather forecast was issued by IMD.';
COMMENT ON COLUMN block_forecasts.forecast_date IS 'Target validity date of the precipitation forecast.';
COMMENT ON COLUMN block_forecasts.rainfall_mm IS 'Forecasted 24-hour rainfall amount in millimeters.';
COMMENT ON COLUMN block_forecasts.source IS 'Data source agency (e.g., IMD, Meghdoot API, WRF).';
COMMENT ON COLUMN block_forecasts.source_model IS 'Underlying numerical model (e.g., GFS, NCUM, WRF-3km).';
COMMENT ON COLUMN block_forecasts.created_at IS 'Timestamp when the record was ingested into the database.';
