-- =============================================================================
-- Migration: Create advisories table in Supabase PostgreSQL
-- Timestamp: 2026-09-07
-- Description: Stores deterministic rule-based agricultural advisories for Panchayats
-- =============================================================================

CREATE TABLE IF NOT EXISTS advisories (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    panchayat_id BIGINT NOT NULL,
    forecast_id BIGINT,
    forecast_date DATE NOT NULL,
    rainfall_mm NUMERIC,
    rainfall_category TEXT,
    severity TEXT,
    advisory_title TEXT,
    advisory_text TEXT,
    rule_version TEXT,
    status TEXT DEFAULT 'DRAFT',
    officer_id TEXT,
    officer_comment TEXT,
    approved_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- =============================================================================
-- INDEXES FOR FAST QUERYING & DASHBOARD FILTERING
-- =============================================================================

-- 1. Index on panchayat_id for rapid village-level advisory lookup
CREATE INDEX IF NOT EXISTS idx_advisories_panchayat_id 
ON advisories (panchayat_id);

-- 2. Index on forecast_date for temporal horizon lookups
CREATE INDEX IF NOT EXISTS idx_advisories_forecast_date 
ON advisories (forecast_date);

-- 3. Index on status for workflow filtering (DRAFT, APPROVED, PUBLISHED, REJECTED)
CREATE INDEX IF NOT EXISTS idx_advisories_status 
ON advisories (status);

-- =============================================================================
-- TABLE & COLUMN DOCUMENTATION COMMENTS
-- =============================================================================

COMMENT ON TABLE advisories IS 'Stores deterministic, rule-based agricultural advisories linked to downscaled panchayat forecasts.';
COMMENT ON COLUMN advisories.id IS 'Primary key auto-generated as identity.';
COMMENT ON COLUMN advisories.panchayat_id IS 'Unique identifier of the Gram Panchayat.';
COMMENT ON COLUMN advisories.forecast_id IS 'Foreign key reference to downscaled_forecasts record (if applicable).';
COMMENT ON COLUMN advisories.forecast_date IS 'Target validity date for which the advisory applies.';
COMMENT ON COLUMN advisories.rainfall_mm IS 'Forecasted downscaled rainfall in millimeters.';
COMMENT ON COLUMN advisories.rainfall_category IS 'Standardized rainfall intensity category (e.g. Light rainfall, Heavy rainfall).';
COMMENT ON COLUMN advisories.severity IS 'Advisory urgency/severity level (LOW, MODERATE, HIGH, CRITICAL).';
COMMENT ON COLUMN advisories.advisory_title IS 'Concise advisory summary headline.';
COMMENT ON COLUMN advisories.advisory_text IS 'Full text / bulleted actionable generic agricultural recommendations.';
COMMENT ON COLUMN advisories.rule_version IS 'Version tag of the deterministic rule applied (e.g., v1.0.0).';
COMMENT ON COLUMN advisories.status IS 'Workflow state of the advisory: DRAFT, APPROVED, PUBLISHED, or REJECTED.';
COMMENT ON COLUMN advisories.officer_id IS 'Identifier of agricultural extension officer reviewing the advisory.';
COMMENT ON COLUMN advisories.officer_comment IS 'Notes, custom adjustments, or sign-off remarks by the officer.';
COMMENT ON COLUMN advisories.approved_at IS 'Timestamp when the advisory was reviewed and approved.';
COMMENT ON COLUMN advisories.created_at IS 'Timestamp when the advisory draft was automatically generated.';
