import { PanchayatItem, AdvisoryItem } from '../types';

export const MOCK_PANCHAYATS: PanchayatItem[] = [
  {
    panchayat_id: 1001,
    lgd_code: 247801,
    panchayat_name: 'Ajmer Saundane',
    block_name: 'Baglan',
    district_name: 'Nashik',
    latitude: 20.6214,
    longitude: 74.1523,
    elevation_m: 540.0,
  },
  {
    panchayat_id: 1002,
    lgd_code: 247802,
    panchayat_name: 'Antapur',
    block_name: 'Baglan',
    district_name: 'Nashik',
    latitude: 20.6512,
    longitude: 74.1894,
    elevation_m: 585.0,
  },
  {
    panchayat_id: 1003,
    lgd_code: 247803,
    panchayat_name: 'Babhulna',
    block_name: 'Baglan',
    district_name: 'Nashik',
    latitude: 20.5901,
    longitude: 74.0921,
    elevation_m: 512.0,
  },
  {
    panchayat_id: 1004,
    lgd_code: 247804,
    panchayat_name: 'Brahmangaon',
    block_name: 'Baglan',
    district_name: 'Nashik',
    latitude: 20.6115,
    longitude: 74.2211,
    elevation_m: 560.0,
  },
  {
    panchayat_id: 1005,
    lgd_code: 247805,
    panchayat_name: 'Dhandri',
    block_name: 'Baglan',
    district_name: 'Nashik',
    latitude: 20.5732,
    longitude: 74.1154,
    elevation_m: 525.0,
  },
  {
    panchayat_id: 1006,
    lgd_code: 247806,
    panchayat_name: 'Jaheda',
    block_name: 'Baglan',
    district_name: 'Nashik',
    latitude: 20.6841,
    longitude: 74.2045,
    elevation_m: 610.0,
  },
  {
    panchayat_id: 1007,
    lgd_code: 247807,
    panchayat_name: 'Kandhane',
    block_name: 'Baglan',
    district_name: 'Nashik',
    latitude: 20.6358,
    longitude: 74.1378,
    elevation_m: 550.0,
  },
  {
    panchayat_id: 1008,
    lgd_code: 247808,
    panchayat_name: 'Mulher',
    block_name: 'Baglan',
    district_name: 'Nashik',
    latitude: 20.7512,
    longitude: 74.0321,
    elevation_m: 720.0,
  },
  {
    panchayat_id: 1009,
    lgd_code: 247809,
    panchayat_name: 'Sompur',
    block_name: 'Baglan',
    district_name: 'Nashik',
    latitude: 20.5982,
    longitude: 74.2415,
    elevation_m: 535.0,
  },
  {
    panchayat_id: 1010,
    lgd_code: 247810,
    panchayat_name: 'Virgaon',
    block_name: 'Baglan',
    district_name: 'Nashik',
    latitude: 20.6124,
    longitude: 74.1089,
    elevation_m: 530.0,
  },
];

export const INITIAL_MOCK_ADVISORIES: AdvisoryItem[] = [
  {
    id: 1,
    panchayat_id: 1001,
    panchayat_name: 'Ajmer Saundane',
    block_name: 'Baglan',
    elevation_m: 540,
    block_forecast_mm: 18.5,
    forecast_id: 101,
    forecast_date: '2026-09-09',
    rainfall_mm: 2.8,
    rainfall_category: 'LIGHT_RAIN',
    severity: 'LOW',
    advisory_title: 'Light Rain Expected — Plan Field Activities Accordingly',
    advisory_text: '• Light rain (2.8 mm) predicted for Ajmer Saundane Gram Panchayat.\n• Favorable conditions for inter-cultivation and field weeding.\n• Safe for chemical foliar spraying in early morning hours.\n• Monitor soil moisture levels in nursery beds and onion plots.',
    status: 'DRAFT',
    rule_id: 'R_MODERATE_RAIN',
    rule_version: 'v1.0.0',
    officer_id: null,
    officer_comment: null,
    approved_at: null,
    created_at: '2026-09-08T06:00:00Z',
  },
  {
    id: 2,
    panchayat_id: 1008,
    panchayat_name: 'Mulher',
    block_name: 'Baglan',
    elevation_m: 720,
    block_forecast_mm: 18.5,
    forecast_id: 102,
    forecast_date: '2026-09-09',
    rainfall_mm: 72.8,
    rainfall_category: 'HEAVY_RAIN',
    severity: 'HIGH',
    advisory_title: 'Heavy Rainfall Warning — High-Elevation Runoff & Drainage Caution',
    advisory_text: '• Heavy rainfall (72.8 mm) predicted due to orographic enhancement around Mulher (elevation 720m).\n• Suspend all tractor operations and fertilizer applications immediately.\n• Create inter-row drainage trenches in tomato and maize fields to prevent waterlogging.\n• Protect nursery beds and vegetable transplants from root-rot and excessive moisture.',
    status: 'DRAFT',
    rule_id: 'R_HEAVY_RAIN',
    rule_version: 'v1.0.0',
    officer_id: null,
    officer_comment: null,
    approved_at: null,
    created_at: '2026-09-08T06:05:00Z',
  },
  {
    id: 3,
    panchayat_id: 1003,
    panchayat_name: 'Babhulna',
    block_name: 'Baglan',
    elevation_m: 512,
    block_forecast_mm: 18.5,
    forecast_id: 103,
    forecast_date: '2026-09-09',
    rainfall_mm: 6.4,
    rainfall_category: 'LIGHT_RAIN',
    severity: 'LOW',
    advisory_title: 'Light Rainfall Expected — Routine Intercultural Operations Permitted',
    advisory_text: '• Light scattered rainfall (6.4 mm) forecasted for Babhulna.\n• Routine weeding, staking, and field preparation may proceed normally.\n• Avoid heavy overhead sprinkler irrigation to conserve energy.\n• Soil moisture is adequate for ongoing standing kharif crop vegetative stages.',
    status: 'APPROVED',
    rule_id: 'R_LIGHT_RAIN',
    rule_version: 'v1.0.0',
    officer_id: 'SMS-AGRI-NASHIK-04',
    officer_comment: 'Verified against local AWS station trends. Recommended routine operations.',
    approved_at: '2026-09-08T07:15:00Z',
    created_at: '2026-09-08T06:10:00Z',
  },
  {
    id: 4,
    panchayat_id: 1005,
    panchayat_name: 'Dhandri',
    block_name: 'Baglan',
    elevation_m: 525,
    block_forecast_mm: 18.5,
    forecast_id: 104,
    forecast_date: '2026-09-09',
    rainfall_mm: 0.8,
    rainfall_category: 'VERY_LIGHT_RAIN',
    severity: 'LOW',
    advisory_title: 'Dry Conditions / Trace Showers — Schedule Supplemental Irrigation',
    advisory_text: '• Very light to trace precipitation (0.8 mm) predicted for Dhandri.\n• Schedule light drip irrigation for cash crops, especially pomegranate and vegetables.\n• Weather is conducive for safe application of bio-pesticides and micronutrient sprays.\n• Monitor topsoil moisture levels across sandy loam plots.',
    status: 'APPROVED',
    rule_id: 'R_VERY_LIGHT_RAIN',
    rule_version: 'v1.0.0',
    officer_id: 'SMS-AGRI-NASHIK-04',
    officer_comment: 'Approved with irrigation schedule reminder.',
    approved_at: '2026-09-08T07:22:00Z',
    created_at: '2026-09-08T06:15:00Z',
  },
  {
    id: 5,
    panchayat_id: 1002,
    panchayat_name: 'Antapur',
    block_name: 'Baglan',
    elevation_m: 585,
    block_forecast_mm: 18.5,
    forecast_id: 105,
    forecast_date: '2026-09-09',
    rainfall_mm: 145.0,
    rainfall_category: 'VERY_HEAVY_RAIN',
    severity: 'CRITICAL',
    advisory_title: 'Very Heavy Rainfall Alert — Extreme Weather Warning',
    advisory_text: '• Severe rainfall anomaly detected (145.0 mm).\n• Discarded preliminary run due to radar calibration drift at neighboring station.\n• Recalibrated model inference requested.',
    status: 'REJECTED',
    rule_id: 'R_VERY_HEAVY_RAIN',
    rule_version: 'v1.0.0',
    officer_id: 'DAO-NASHIK-HEAD',
    officer_comment: 'Rejected: Model anomaly detected due to sensor variance. Recalibration scheduled.',
    approved_at: null,
    created_at: '2026-09-08T05:30:00Z',
  },
];
